DROP DATABASE IF EXISTS `19wh1a1287`;
CREATE SCHEMA 19wh1a1287;
USE 19wh1a1287;
CREATE TABLE bus(bus_no INT , bus_type VARCHAR(20) , source VARCHAR(30) , destination VARCHAR(30) );
INSERT INTO bus VALUES(4590 , 'PRIVATE' , 'Mahabubabad' , 'Warangal');
INSERT INTO bus VALUES(5409 , 'PUBLIC' , 'Adilabad' , 'Hyderabad');
INSERT INTO bus VALUES(4095 , 'PUBLIC' , 'Khammam' , 'Mahaboobnagar');
INSERT INTO bus VALUES(9054 , 'PRIVATE' , 'Karimnagar' , 'Bhadrachalam');
SELECT * FROM bus ;
DELETE FROM bus b WHERE b.bus_no = 5409;
SELECT * FROM bus ;
UPDATE bus b SET b.bus_no=bus_no-1;
SELECT * FROM bus ;
CREATE TABLE Passanger(id INT , name VARCHAR(20) ,age INT , gender VARCHAR(10), source VARCHAR(30) , destination VARCHAR(30) );
INSERT INTO Passanger VALUES(05 , 'Preetham' ,19, 'F','Hyderabad' , 'Thorrur' );
INSERT INTO Passanger VALUES(10 , 'Rakesh' ,89, 'M','Hyderabad' , 'Bhutan' );
INSERT INTO Passanger VALUES(12 , 'Thanu' ,35,'F', 'Hyderabad' , 'Wyra' );
INSERT INTO Passanger VALUES(20 , 'Aadhya' ,68, 'M','Hyderabad' , 'Medak' );
SELECT * FROM Passanger ;
DELETE FROM Passanger P WHERE P.name = 'priya';
SELECT * FROM Passanger ;
UPDATE Passanger P SET P.age = age - 5;
SELECT * FROM Passanger ;
CREATE TABLE Ticket(ticket_type VARCHAR(20) ,ticket_no INT , amount INT , source VARCHAR(30) , destination VARCHAR(30) , name VARCHAR(20));
INSERT INTO Ticket VALUES('FULL' , 05 , 200 , 'Hyderabad' , 'Thorrur', 'priya');
INSERT INTO Ticket VALUES('HALF' , 10 , 50, 'Warangal' , 'Thorrur' ,'harish');
INSERT INTO Ticket VALUES('FULL' , 12 , 100, 'Warangal' , 'Thorrur','Tejaswini' );
INSERT INTO Ticket VALUES('HALF' , 20 , 100, 'Hyderabad' , 'Thorrur','akshay' );
SELECT * FROM Ticket ;
DELETE FROM Ticket t WHERE ticket_no = 405;
SELECT * FROM Ticket ;
UPDATE Ticket T SET T.ticket_type = "FULL";
SELECT * FROM Ticket ;
CREATE TABLE Reservation(type VARCHAR(20) , seat_no INT ,  source VARCHAR(30) , destination VARCHAR(30) );
INSERT INTO Reservation VALUES('Offline' , 05 , 'Warangal' , 'Thorrur' );
INSERT INTO Reservation VALUES('Online' , 10 , 'Warangal' , 'Mahabubabad' );
INSERT INTO Reservation VALUES('Offline' , 15 , 'Warangal' , 'Hyderabad' );
SELECT * FROM Reservation ;
DELETE FROM Reservation R WHERE R.destination = 'Thorrur';
SELECT * FROM Reservation ;
UPDATE Reservation R SET R.source = "Delhi";
SELECT * FROM Reservation ;
CREATE TABLE Cancellation(bus_no INT , ticket_no INT , seat_no INT , name VARCHAR(20)); 
INSERT INTO Cancellation VALUES(4590 , 405, 05 , 'priya'); 
INSERT INTO Cancellation VALUES(5490 , 408, 32 , 'Akshay');
INSERT INTO Cancellation VALUES(4507 , 580, 21 , 'rani');
SELECT * FROM Cancellation ;
ALTER TABLE Cancellation ADD COLUMN age INT ;
DELETE FROM Cancellation C WHERE C.name = 'sai';
SELECT * FROM Cancellation ;
UPDATE Cancellation C SET C.seat_no = seat_no + 5;
SELECT * FROM Cancellation ;
SELECT DISTINCT P.id FROM passanger P;
SELECT P.name FROM Passanger P WHERE P.gender ='M'; 
SELECT DISTINCT P.id , P.name FROM passanger P;
SELECT P.name FROM Passanger P WHERE P.name LIKE 'R%h';
SELECT P.name FROM Passanger P WHERE P.age >= 30 AND P.age <= 45;
SELECT P.name FROM Passanger P WHERE P.name like 'a%';
SELECT P.name FROM Passanger P ORDER by P.name ;